---
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径 
  type-aliases-package: com.atguigu.springcloud.entities  
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring:
  application:
    name: microservicecloud-dept         #很重要
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 1234
    dbcp2:
      min-idle: 5           #数据库连接池的最小维持连接数
      initial-size: 5       # 初始化连接数
      max-total: 5          # 最大连接数
      max-wait-millis: 200  # 等待连接获取的最大超时时间
  profiles:
    active: dev
logging:
    level: 
      com.atguigu.springcloud.dao: debug
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactid: $project.artifactid$
  build.version: $project.version$
  author: 段朝旭
---
server:
  port: 8001  
spring:
 profiles: dev   
---
server:
  port: 8002  
spring:
 profiles: test 