spring:
 profiles:
  active:
   - dev

---
server:
  port: 7001
spring:
 profiles: dev
eureka:
  #server:
  #  enable-self-preservation: false   禁用自我保护机制，一般不推荐
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false  #false 表示 自己就是注册中心，我的 职责 是维护 服务示例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001
spring:
 profiles: test
eureka:
  #server:
  #  enable-self-preservation: false   禁用自我保护机制，一般不推荐
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false  #false 表示 自己就是注册中心，我的 职责 是维护 服务示例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/     